# Generated by Django 4.2.7 on 2023-12-02 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_date_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(max_length=30, verbose_name='Teaching Language')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Hourly Rate')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, default='2000-01-01', verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=7, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_pnone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Number_pnone'),
        ),
    ]
