# Generated by Django 4.2.7 on 2023-12-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_teacher_user_birthday_user_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_pnone',
        ),
        migrations.AddField(
            model_name='user',
            name='number_phone',
            field=models.CharField(default=0, max_length=10, unique=True, verbose_name='Number_phone'),
            preserve_default=False,
        ),
    ]
