# Generated by Django 4.2.7 on 2023-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_teacher_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Polish', 'Polish'), ('Ukrainian', 'Ukrainian'), ('French', 'French'), ('German', 'German')], max_length=15, verbose_name='Teaching Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='Birthday'),
        ),
    ]
