# Generated by Django 4.2.7 on 2023-12-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_teacher_language_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('Ukrainian', 'Ukrainian'), ('French', 'French'), ('Polish', 'Polish')], max_length=15, verbose_name='Teaching Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=15, verbose_name='Password'),
        ),
    ]
