# Generated by Django 4.2.7 on 2023-12-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_teacher_language_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('Polish', 'Polish'), ('German', 'German'), ('French', 'French'), ('English', 'English'), ('Ukrainian', 'Ukrainian')], max_length=15, verbose_name='Teaching Language'),
        ),
    ]
