# Generated by Django 4.2.7 on 2023-12-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_teacher_language_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('German', 'German'), ('French', 'French'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish'), ('English', 'English')], max_length=15, verbose_name='Teaching Language'),
        ),
    ]
