# Generated by Django 4.2.7 on 2023-12-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('French', 'French'), ('German', 'German'), ('Polish', 'Polish'), ('Ukrainian', 'Ukrainian')], max_length=15, verbose_name='Teaching Language'),
        ),
    ]
