# Generated by Django 5.0 on 2023-12-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('French', 'French'), ('Ukrainian', 'Ukrainian'), ('Polish', 'Polish'), ('German', 'German'), ('English', 'English')], max_length=15, verbose_name='Teaching Language'),
        ),
    ]
