# Generated by Django 5.0 on 2023-12-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_user_status_email_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('Ukrainian', 'Ukrainian'), ('French', 'French'), ('English', 'English'), ('Polish', 'Polish'), ('German', 'German')], max_length=15, verbose_name='Teaching Language'),
        ),
    ]
