# Generated by Django 5.0 on 2023-12-17 17:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_teacher_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('French', 'French'), ('German', 'German'), ('English', 'English'), ('Polish', 'Polish'), ('Ukrainian', 'Ukrainian')], max_length=15, verbose_name='Teaching Language'),
        ),
    ]
