# Generated by Django 5.0 on 2023-12-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_user_email_confirmation_token_alter_teacher_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='language',
            field=models.CharField(blank=True, choices=[('Polish', 'Polish'), ('English', 'English'), ('German', 'German'), ('Ukrainian', 'Ukrainian'), ('French', 'French')], max_length=15, verbose_name='Teaching Language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student')], max_length=7, verbose_name='Role'),
        ),
    ]
